
function [converged, U_out,reaction, iter] = newtonLoop(obj,F_external,U_curr,fixed_dofs)

nDofs=length(U_curr);
% Initialize free DOFs for the Newton loop
free_dofs = setdiff(1:nDofs, fixed_dofs);

% Newton Loop
for iter = 1:obj.Options.MaxIterations

    % 1. Get Tangent Stiffness & Internal Force
    [Kt, F_int] = obj.assembleTangentSystem(U_curr);
    % [Kt, F_int] = obj.Model.assembleTangentStiffness(U_curr);

    % 2. Calculate Residual (R = F_ext - F_int)
    R = F_external - F_int;

    % Check Convergence (Force Norm on Free DOFs)
    % The extra convergence criteria can be implemented for faster or more
    % flexible e.g., energy,moment,...
    err = norm(R(free_dofs));
    if err < obj.Options.Tolerance
        converged = true;
        U_out = U_curr;
        reaction=F_int(fixed_dofs);
        return;
    end

    % 3. Solve for dU
    % K_ff * dU_f = R_f
    % Note: For Disp control, the "Prescribed" part is already in U_curr,
    % so R accounts for the forces generated by that movement.

    % if rcond(Kt(free_dofs, free_dofs)) < 1e-15
    %     % Singular Matrix (Instability)
    %     converged = false; U_out = U_curr; return;
    % end

    dU_f = Kt(free_dofs, free_dofs) \ R(free_dofs);

    % 4. Update
    U_curr(free_dofs) = U_curr(free_dofs) + dU_f;

end

% If loop finishes without returning, we failed
U_out = U_curr;
reaction=[];
converged = false;
end